### ISSUE TITLE
Thumbnails for Webtoons.com do not load

### ISSUE THREAD

**Issue by joseph619** [NerdNumber9/TachiyomiEH#60] opened 2019-04-07 14:32 UTC
**App version:** 8.2.0

**Android version:** 9.0

**Issue/Request:** Thumbnails and info don't work for Webtoons.com

Webtoons.com thumbnails and manga info (Artist, Status etc) do not load for TachiyomiEH. It works fine for Tachiyomi 0.8.2. 

Here are the screenshots. 

Error code: **Did not find balanced marker at 'alt=Representative image'**

![0-02-01-02d97abba27ae2f6c465ae5cf44bf3460079613e7ce4b9188141933034ec1b75_1fd87f27](https://user-images.githubusercontent.com/34897862/55685082-55833b00-5920-11e9-8efd-af8b9fbb1ceb.jpg)
![0-02-01-d117b21c6e5a5d7dedf87b181ce0ccc511b19436c4d17218d9b54ecdb07fb40e_a750f8e8](https://user-images.githubusercontent.com/34897862/55685083-55833b00-5920-11e9-8054-a7c139abd6d6.jpg)

**Comment by NerdNumber9** [comment] 2019-04-07 17:08
I'm just going to leave a note here for myself so I know how to fix this issue:

Caused by invalid CSS selector: https://github.com/inorichi/tachiyomi-extensions/blob/bf68665bc47e3168ec4363ceaf2cc88fa984f4f0/src/en/webtoons/src/eu/kanade/tachiyomi/extension/en/webtoons/Webtoons.kt#L128

Issue was introduced when we upgraded JSoup and JSoup started using stricter CSS selector validation (https://github.com/jhy/jsoup/commit/8fecf72da0c9d1d6da7ec1aab0214ff68588da88).

**Comment by NerdNumber9** [comment] 2019-04-13 11:08
This is fixed now. Re-install the Webtoons extension to get the fix.

**Closed as completed by NerdNumber9** 2019-04-13 11:08 UTC
