### ISSUE TITLE
Download problem.

### ISSUE THREAD

**Issue by ichijoraku** [NerdNumber9/TachiyomiEH#12] opened 2018-02-03 04:44 UTC
I can't still download the app. Either invalid link or download failed.

**Comment by NerdNumber9** [comment] 2018-02-03 04:47
Can you download it from this link? https://github.com/NerdNumber9/TachiyomiEH/releases/download/v6.8.0-EH/app.apk

**Comment by ichijoraku** [comment] 2018-02-03 05:40
Download app.apk failed. Please try agian. I was using default browser, opera mini old and latest and UC browser.

**Comment by ichijoraku** [comment] 2018-02-03 05:57
I even used android IDM ... 
Is it because of the link ? I tried to download the regular tachiyomi and I successfully downloaded it.

**Comment by ichijoraku** [comment] 2018-02-03 09:21
Download successful. I used pc. probably my phone was the problem..

**Comment by NerdNumber9** [comment] 2018-02-03 16:15
Hmm, not sure what the problem is here. I assume you have this all sorted out so I will close this issue now.

**Closed as completed by NerdNumber9** 2018-02-03 16:15 UTC
