### ISSUE TITLE
[Enhancement Request] Add an option to remove "Finished / Next" page

### ISSUE THREAD

**Issue by clem193** [NerdNumber9/TachiyomiEH#64] opened 2019-04-12 21:31 UTC
As said in the title, would it be possible to add an option to remove the "Finished / Next" page that appear between each chapter since recent EH updates ? 

I know many people (myself included) that are very annoyed by this feature, especially when reading short chapters mangas/webtoons (it even breaks webtoons flow), best examples would be 4Koma or very short webtoons chapters like Winter Moon.

If I wanna know my current chapter I can just tap on my screen once and it will give me all the information I need, I don't need a forced page to remind it to me nonstop. Seeing this page appearing every 2 - 10 pages is very intrusive and annoying in the long run (Not what I want in my beloved reader i'm using since years).

From what I understood this fake page got added as a "buffer" so the app start downloading/loading next/previous chapter, but personally I was fine and never had loading issue or whatsoever with the old system before this buffer page appear.

So yeah, would it be possible to at least make an option for people who don't want it ?

Thanks for your time.

**Comment by NerdNumber9** [comment] 2019-04-12 23:07
Related to: https://github.com/inorichi/tachiyomi/issues/1653

**Comment by NerdNumber9** [comment] 2019-04-13 03:04
Spent 4 hours on this...

I've managed to remove the page in the Vertical, Left-to-Right and Right-to-Left viewers.

It also partially works in the Webtoon viewer but can be buggy if each chapter of the manga has only one page. Fixing this would probably involve a pretty large rewrite of the Webtoon viewer which I don't exactly feel like doing right now...

This feature will be included in the next release.

**Closed as completed by NerdNumber9** 2019-04-13 03:04 UTC

**Comment by Dimava** [comment] 2019-04-18 09:31
For webtoon viewer feature may be implemented by shrinking chapter-break to height of loading circle and hiding text.
Chapter-break itself is barely noticeable, the problem is it's somewhat tall and distracts with text.

**Comment by NerdNumber9** [comment] 2019-04-18 15:39
That's actually very similar to what I did. I shrunk the break down to size 0. This seems to cause problems however... I'll see what happens if I shrink it down to a thin 1-pixel line.
