### ISSUE TITLE
App crash at startup

### ISSUE THREAD

**Issue by vicokoby** [NerdNumber9/TachiyomiEH#69] opened 2019-04-19 16:00 UTC
**App version:** 8.4.0

**Android version:** 5.0

**Issue/Request:** App crash at startup

**Steps to reproduce (if applicable)**

 1. Launch new TachiyimoEH v8.4.0
 2. App crash
 
**Other details:**
I cannot install a lower version and I'm afraid of losing my library.

**Comment by sprite-1** [comment] 2019-04-19 16:51
I'm getting this too. I don't want to clear my library data as I haven't backed it up in so long and I don't want to lose my collection built up over the years 🙁️

**Comment by NerdNumber9** [comment] 2019-04-19 17:02
~~I'm currently working on finding the cause of this issue.~~ DO NOT CLEAR APP DATA OR UNINSTALL, you will lose your data. Once I find it I'll release a fix for it right away. 

You don't have to worry about losing your data AS LONG AS YOU DONT CLEAR THE APP DATA/UNINSTALL because since I knew this update was very large, I had the app automatically make a backup of your library after you installed it. This backup is still stored in the app's data however so if you clear app data or uninstall, it will be deleted.

Issue found, release with fix will be out shortly.

**Comment by sprite-1** [comment] 2019-04-19 17:08
Yeah, I was about to ask if there was a way to retrieve the old data so I can clear. Gad I didn't, thanks for all the effort man :+1:

**Comment by NerdNumber9** [comment] 2019-04-20 03:12
Fixed in latest release.

**Closed as completed by NerdNumber9** 2019-04-20 03:12 UTC
